#!/bin/sh

usage() {
  echo "$0 - take a screenshot and output to stdout, portably"
  exit 0
}

die() {
  echo >&2 "error: $@"
  exit 1
}

# get user options
while [ $# -gt 0 ]; do
  # get options
  arg="$1"
  shift

  case "$arg" in
  -h|--help) usage ;;
  --*)
    die "unrecognised option: '$arg'\n$usage" ;;
  *)
    die "unrecognised argument" ;;
  esac
done

darwin_screencap() {
  screencapture -i "$1"
}

linux_screencap() {
  if type import >/dev/null
  then
    import "$1"
  elif type shutter >/dev/null
  then
    shutter -e -o "$1"
  elif type scrot >/dev/null
  then
    scrot "$1"
  else
    die "cannot find a supported screen capture tool
please install a supported one:
    imagemagick
    shutter
    scrot"
  fi
}

all_screencap() {
  case $(uname) in
  Darwin) darwin_screencap "$1" ;;
  Linux) linux_screencap "$1" ;;
  *) die "screencap not implemented for $(uname)" ;;
  esac
}

date=$(date +"%Y-%m-%dT%H:%M:%SZ")
fpath=$(mktemp /tmp/screencap.$date.XXXXXX.png)
all_screencap "$fpath" || die "capture failed"
echo "Capture is in '$fpath'"

